export const MAIN_URL = process.env.NEXT_PUBLIC_APP_URL
export const NEXT_APPWRITE_KEY = process.env.NEXT_APPWRITE_KEY
export const NEXT_PUBLIC_APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT
export const NEXT_PUBLIC_APPWRITE_PROJECT = process.env.NEXT_PUBLIC_APPWRITE_PROJECT
export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!
export const AUTH_COOKIE = "cwa-jira-clone-session"
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!
export const IMAGES_BUCKET_ID=process.env.NEXT_PUBLIC_IMAGES_BUCKET_ID!